
multitenancy:
  strategy: SCHEMA
  dataSource:
    tenantId: default
    url: jdbc:postgresql://database-postgres.desenv-local:5432/multitenancy_schema
    username: postgres
    password: changeit
    driverClassName: org.postgresql.Driver
